"""add_customer_support_system

Revision ID: 54755819609c
Revises: 57a464b5fa32
Create Date: 2026-06-16 17:38:54.951442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54755819609c'
down_revision = '57a464b5fa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.String(length=8), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_ticket_created', sa.Boolean(), nullable=False),
    sa.Column('email_ticket_assigned', sa.Boolean(), nullable=False),
    sa.Column('email_status_changed', sa.Boolean(), nullable=False),
    sa.Column('email_new_comment', sa.Boolean(), nullable=False),
    sa.Column('email_sla_warning', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('sla_response_due', sa.DateTime(), nullable=True),
    sa.Column('sla_resolution_due', sa.DateTime(), nullable=True),
    sa.Column('sla_response_met', sa.Boolean(), nullable=False),
    sa.Column('sla_resolution_met', sa.Boolean(), nullable=False),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('priority_change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('support_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_notifications_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('ticket_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_assignments_assigned_by_id'), ['assigned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_assignments_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_assignments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_comments_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_comments_user_id'), ['user_id'], unique=False)

    op.create_table('ticket_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_email', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status_history_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['ticket_comments.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachments_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_attachments_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='customer'))
        batch_op.add_column(
            sa.Column('availability_status', sa.String(length=20), nullable=False, server_default='available')
        )
        batch_op.add_column(sa.Column('expertise_areas', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', server_default=None)
        batch_op.alter_column('availability_status', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('expertise_areas')
        batch_op.drop_column('availability_status')
        batch_op.drop_column('role')

    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_comment_id'))

    op.drop_table('ticket_attachments')
    with op.batch_alter_table('ticket_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_status_history_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_status_history_created_at'))

    op.drop_table('ticket_status_history')
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_comments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_comments_created_at'))

    op.drop_table('ticket_comments')
    with op.batch_alter_table('ticket_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_assignments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_assignments_assigned_to_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_assignments_assigned_by_id'))

    op.drop_table('ticket_assignments')
    with op.batch_alter_table('support_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_notifications_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_support_notifications_created_at'))

    op.drop_table('support_notifications')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_customer_email'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_category'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_assigned_to_id'))

    op.drop_table('support_tickets')
    op.drop_table('notification_preferences')
    op.drop_table('ticket_counters')
    # ### end Alembic commands ###
